#!/bin/sh
#SBATCH -J ht
#SBATCH -o job-%j.log
#SBATCH -e job-%j.err
#SBATCH -N 1 -n 48
#SBATCH -p normal
echo Time is `date`
echo Directory is $PWD
echo This job runs on the following nodes:
echo $SLURM_JOB_NODELIST
echo This job has allocated $SLURM_JOB_CPUS_PER_NODE cpu cores.
module add vasp/5.4.4-intel2019

cordlist=('cord1')
for rows in `cat formula_list.txt`
do
material=`echo $rows | sed 's/[^0-9a-Z]//g'`
if [ -d $material ]; then
for cordprefix in ${cordlist[@]}
do
        cd ./$material/$cordprefix
        for cordf in `ls`
        do
        if [ -d $cordf ]; then
                cd ./$cordf
                mpirun vasp_std_2D > runlog
                if test -s CONTCAR
                then
                        cp CONTCAR POSCAR
                        mpirun vasp_std_2D > runlog
                fi
                cd ..
        fi
        done
        cd ../..
done
fi
done

