#!/bin/sh
#SBATCH -J ht
#SBATCH -o job-%j.log
#SBATCH -e job-%j.err
#SBATCH -N 1 -n 48
#SBATCH -p long
echo Time is `date`
echo Directory is $PWD
echo This job runs on the following nodes:
echo $SLURM_JOB_NODELIST
echo This job has allocated $SLURM_JOB_CPUS_PER_NODE cpu cores.
module add vasp/5.4.4-intel2019

cordlist=('cord2' 'cord3' 'cord4' 'cord5')
for rows in `cat formula_list.txt`
do
material=`echo $rows | sed 's/[^0-9a-Z]//g'`
if [ -d $material ]; then
for cordprefix in ${cordlist[@]}
do
        cd ./$material
        if [ -d $cordprefix ]; then
                cd ./$cordprefix
                for cordf in `ls`
                do
                if [ -d $cordf ]; then
                        cd ./$cordf/scf
                        mpirun vasp_std_2D > runlog
                        cd ../band
                        cp ../scf/CHG* ./
                        mpirun vasp_std_2D > runlog
                        cd ../..
                fi
                done
                cd ../..
        else
                cd ..
        fi
done
fi
done
